# Generated by Django 2.0 on 2021-08-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210522_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='owner',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Books&Sports', 'Books&Sports'), ('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Jobs', 'Jobs'), ('Cars', 'Cars'), ('Electronics', 'Electronics'), ('Mobiles', 'Mobiles'), ('Bikes', 'Bikes'), ('Property', 'Property')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('UK', 'Uttarakhand'), ('MZ', 'Mizoram'), ('HP', 'Haryana'), ('OD', 'Odisha'), ('AR', 'Arunachal Pradesh'), ('BR', 'Bihar'), ('MH', 'Maharashtra'), ('GA', 'Goa'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MN', 'Manipur'), ('PB', 'Punjab'), ('JH', 'Jharkhand'), ('TS', 'Telegana'), ('CG', 'Chhattisgarh'), ('TN', 'Tamil Nadu'), ('RJ', 'Rajasthan'), ('MI', 'Sikkim'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal'), ('GJ', 'Gujarat'), ('ML', 'Meghalaya'), ('TR', 'Tripura'), ('AS', 'Assam'), ('NL', 'Nagaland'), ('KA', 'Karnataka'), ('AP', 'Andhra Pradesh')], max_length=100),
        ),
    ]
